name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK17
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 17
          distribution: corretto

      - name: Clone secure submodule
        run: |
          git submodule update --init --recursive --depth 2
      - name: Fetch sensitive file from secure submodule
        run: |
          cp ./secret/config/application-prod.yml ./src/main/resources/application.yml
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Image build and push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_ID }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build --build-arg DEPENDENCY=build/dependency -t ${{ secrets.DOCKER_REPO_NAME }}/springboot-app:latest --platform linux/amd64 .
          docker push ${{ secrets.DOCKER_REPO_NAME }}/springboot-app:latest

      - name: Upload docker-compose yaml script to artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: ${{ github.workspace }}/secret/config/app-docker-compose.yml

  deploy:
    runs-on: ${{ matrix.instance }}
    needs: build
    strategy:
      matrix:
        instance: [ "web-app-a", "web-app-b" ]

    steps:
      - name: Set docker-compose YAML script to runner
        uses: actions/download-artifact@v4
        with:
          name: docker-compose
          path: ${{ github.workspace }}

      - name: Copy docker-compose YAML
        run: |
          sudo rsync -av --ignore-existing app-docker-compose.yml ${{ secrets.DOCKER_COMPOSE_YAML_PATH }}/

      - name: Stop and remove the old environment
        run: |
          sudo docker-compose -f ${{ secrets.DOCKER_COMPOSE_YAML_PATH }}/app-docker-compose.yml -p ${{secrets.SERVER_PORT}} down

      - name: Start the new environment
        run: |
          sudo docker-compose -f ${{ secrets.DOCKER_COMPOSE_YAML_PATH }}/app-docker-compose.yml -p ${{secrets.SERVER_PORT}} up -d
