name: CI

on: 
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: true 

      - name: Set up JDK17
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 17
          distribution: corretto
          
      - name: Clone secure submodule
        run: |
          git submodule update --init --recursive --depth 1

      - name: Fetch sensitive file from secure submodule
        run: |
          ls -al | cat 
          echo hello
          cat secret/application.yml
