name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK17
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 17
          distribution: corretto

      - name: Clone secure submodule
        run: |
          git submodule update --init --recursive --depth 2

      - name: Fetch sensitive file from secure submodule
        run: |
          cp ./secret/config/application.yml ./src/main/resources/application.yml
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Running Test Code
        run: ./gradlew --info test
